% Relationship between columns in out.dataMat and out.dataMap or dataMat
% and DataMap and behavior

% Dot trials
par.idx = struct('dot_on'    ,  1, ...
    'dot_off'       ,  2, ...
    'saccade'       ,  3, ...
    'dot_dir'       ,  4, ...
    'dot_coh'       ,  5, ...
    'sig_coh'       ,  6, ...
    'seed_base'     ,  7, ...
    'seed_var'      ,  8, ...
    'correct'       ,  9, ...
    'cho_trg'       , 10, ...
    'rt'            , 11, ...
    'dot_dur'       , 12, ...
    'dot_sp'        , 13, ...
    'dot_apr'       , 14,  ...
    'task'          , 15,  ... % NSt 18-09-04: 1 = eye; 2 = hand (effector supposed to be used)
    'effector'      , 16,  ... % NSt 18-08-29: 1 = eye; 2 = hand (effector used)
    'targ_acq'      , 17,...   % NSt 19-01-05: time to target being acquired
    'fix_x'         , 18,...
    'fix_y'         , 19,...
    'targ1_x'       , 20,...
    'targ1_y'       , 21,...
    'targ2_x'       , 22,...
    'targ2_y'       , 23,...
    't_targPres'    , 24,...    % Added for Gabe's data --> should add to Neo as well
    'pulseTrial'    , 25,...    % Added for Gabe's data --> should add to Neo as well
    't_pulseon'     , 26, ...   % Time of pulse onset
    't_pulseoff'    , 27, ...   % Time of pulse offset
    'pulseSize'     , 28, ...   % signed pulse size (pulse size * pulse direction)
    'pulseDur'      , 29, ...   % Pulse duration
    'pulseCoh'      , 30,...    % absolute coherence during pulse
    'trialid'       , 31,...    % Task ID - not currently used
    'rewDur'        , 32);      % Reward size

% Mapping trials
par.idxMap = struct('t_fpOn',   1, ...
    't_targPres',   2, ...
    't_targOff',    3, ...
    't_fpOff',      4, ...
    't_response',   5, ...
    't_targ_acq',   6, ...
    'targDelay',    7, ...
    'targDur',      8, ...
    'fixHold',      9, ...
    'goRT',         10, ...
    'respDur',      11, ...
    'targ_x',       12, ...
    'targ_y',       13, ...
    'task',         14, ...    % 1 = eye; 2 = hand (effector supposed to be used)
    'effector',     15, ...    % 1 = eye; 2 = hand (effector used)
    'overMem',      16,...
    'fix_x',        17,...
    'fix_y',        18,...
    'trialid',      19,...
    'trg_ct',       20,...      % target count: number of target within trial
    'trlNum',       21,...        % trial number (ignoring target count)
    't_fpOnEye',   22, ...
    't_targPresEye',   23, ...
    't_targOffEye',    24, ...
    't_fpOffEye',      25, ...
    't_responseEye',   26, ...
    't_targ_acqEye',   27);


